### ISSUE TITLE
Add support for float (X Axis)

### ISSUE THREAD

**Issue by MistressPlague** [DevSlem/unity-move-tool#10]
It'd be nice to have a option for single-axis (x) via applying the attrib to a float. (aka a singular vector)

**Comment by DevSlem** [comment]
You mean that `MoveTool` attribute can be defined for `float` type field and move the position handle along the x axis. It is right?
Thank you for your opinion. I will soon add it.

**Comment by MistressPlague** [comment]
Correct. Another useful thing would be a method can call from our scripts to draw movetools for in-method variables, since attributes in my own editor script wouldn't end very well; always being on.

**Comment by MistressPlague** [comment]
Discord is Kanna#0003 if you want more info on use cases.

**Comment by DevSlem** [comment]
I added the feature. You can now use **Move-Tool** for the `float` field in [Release 3.1.0](https://github.com/DevSlem/unity-move-tool/releases/tag/release-3.1.0).
